# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Clusternator Documentation
description: > # this means to ignore newlines until "baseurl:"
  The Clustenator is a container deployment tool designed to help front end web
  developers manage deployments in their continuous integration flow. The
  Clusternator currently works with Docker, and Amazon's AWS cloud service.
baseurl: "/the-clusternator" # the subpath of your site, e.g. /blog
url: "http://the-clusternator.rangle.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
